server:
  port: 8800
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lksun.cn:3306/lkschool?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: lkschool
    password: lkschool
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
logging:
  level:
    root: info
jwt:
  tokenHeader: Authorization
  secret: secret
  expiration: 3600
  tokenHead: Bearer